#import "iCore.h"
#import "iHttp.h"
#import "iStringUtils.h"
#import "iSQL.h"
#import "iPhone.h"
#import "iJSON.h"
#import "iHUD.h"
#import "iNetwork.h"
#import "iEncryption.h"
#import "iRandomAccessFile.h"
#import "iSideMenu.h"
#import "iReleaseLogger.h"
@class b4i_main;
@class b4i_actmenu;
@class b4i_library;
@class b4i_actsearch;
@class b4i_actregister;
@class b4i_actcontact;
@class b4i_actproduct;
@class b4i_actpicture;
@class b4i_actdoorder;
@class b4i_actcategory;
@class b4i_actpayment;
@class b4i_actpush;
@class b4i_pushnotification;
@class b4i_actlogin;
@class b4i_actbasket;
@class b4i_actproducts;
@class b4i_actsms;
@class b4i_actorderdetails;
@class b4i_modshare;
@class b4i_acterrorinternet;
@class b4i_httputils2service;
@class b4i_cachedata;
@class b4i_dateutils;
@class b4i_bookmark;
@class b4i_actabout;
@class b4i_actshow;
@class b4i_actweb;
@class b4i_actsetting;
@class b4i_actreview;
@class b4i_peroperties;
@class _responseadditem;
@class b4i_imagedownloader;
@class b4i_opencart;
@class _multipartfiledata;
@class b4i_httpjob;
@class b4i_clspreferencemanager;
@class b4i_slidemenu;
@class b4i_richstring;
@class b4i_html;
@class b4i_mytoastmessageshow;
@class b4i_customlistview;
@class _period;
@class b4i_imagezoom;
@interface b4i_actaccount : B4IStaticModule
- (NSString*)  _addaddress_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _btnadd_address_click;
- (NSString*)  _btnadd_click;
- (NSString*)  _btnaddress_click;
- (NSString*)  _btnapply_newsletter_click;
- (NSString*)  _btnback_menu_click;
- (NSString*)  _btncancel_new_address_click;
- (NSString*)  _btncancel_return_click;
- (NSString*)  _btnclose_click;
- (NSString*)  _btndefault_address_click;
- (NSString*)  _btndelete_address_click;
- (NSString*)  _btndetails_click;
- (NSString*)  _btnedit_address_click;
- (NSString*)  _btnorders_click;
- (NSString*)  _btnpassword_click;
- (NSString*)  _btnpasswords_click;
- (NSString*)  _btnprofile_click;
- (NSString*)  _btnreturn_details_click;
- (NSString*)  _btnreturns_click;
- (NSString*)  _btnsave_click;
- (NSString*)  _btnscribe_click;
- (NSString*)  _changepassword_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _changeviewsetting;
- (NSString*)  _city_receive:(B4IList*) _res :(NSString*) _cat;
- (NSString*)  _country_receive:(B4IList*) _ls :(NSString*) _cat;
- (NSString*)  _defaultbuttonmenucolor;
- (NSString*)  _deleteaddress_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _detailsorder_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _editaddress_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _getdetails_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _hidemainpanelsv;
- (NSString*)  _lbladdress_1_click;
- (NSString*)  _listaddress_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _orders_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _pageaccount_appear;
- (NSString*)  _pageaccount_disappear;
- (NSString*)  _process_globals;
@property (nonatomic)NSString* _choosentab;
@property (nonatomic)B4ITimer* _tmropenmenu;
@property (nonatomic)B4IScrollView* _svreturns;
@property (nonatomic)B4IButtonWrapper* _btnsave;
@property (nonatomic)B4ILabelWrapper* _label11;
@property (nonatomic)B4ILabelWrapper* _label2;
@property (nonatomic)B4ILabelWrapper* _label3;
@property (nonatomic)B4ILabelWrapper* _label5;
@property (nonatomic)B4ILabelWrapper* _label7;
@property (nonatomic)B4ILabelWrapper* _label9;
@property (nonatomic)B4ILabelWrapper* _lbldate;
@property (nonatomic)B4ILabelWrapper* _lblemail;
@property (nonatomic)B4ILabelWrapper* _lblfamily;
@property (nonatomic)B4ILabelWrapper* _lblfax;
@property (nonatomic)B4ILabelWrapper* _lblip;
@property (nonatomic)B4ILabelWrapper* _lblname;
@property (nonatomic)B4ILabelWrapper* _lblpassword;
@property (nonatomic)B4ILabelWrapper* _lblphone;
@property (nonatomic)B4ITextFieldWrapper* _txtemail;
@property (nonatomic)B4ITextFieldWrapper* _txtfamily;
@property (nonatomic)B4ITextFieldWrapper* _txtfax;
@property (nonatomic)B4ITextFieldWrapper* _txtname;
@property (nonatomic)B4ITextFieldWrapper* _txtpassword;
@property (nonatomic)B4ITextFieldWrapper* _txtphone;
@property (nonatomic)B4IButtonWrapper* _btnpassword;
@property (nonatomic)B4ILabelWrapper* _lblcountry;
@property (nonatomic)B4IPickerWrapper* _txtcountry;
@property (nonatomic)B4ILabelWrapper* _lblcity;
@property (nonatomic)B4IPickerWrapper* _txtcity;
@property (nonatomic)B4ILabelWrapper* _lbladdress;
@property (nonatomic)B4IButtonWrapper* _btnadd;
@property (nonatomic)B4IList* _listcity;
@property (nonatomic)B4IList* _listcountries;
@property (nonatomic)B4ITextFieldWrapper* _txtaddress;
@property (nonatomic)B4IPickerWrapper* _lvaddress;
@property (nonatomic)B4IPickerWrapper* _listcountry;
@property (nonatomic)B4ILabelWrapper* _lblid;
@property (nonatomic)B4ILabelWrapper* _lblstate2;
@property (nonatomic)B4IButtonWrapper* _btndetails;
@property (nonatomic)B4IPanelWrapper* _pnlorder;
@property (nonatomic)B4IButtonWrapper* _btnadd_address;
@property (nonatomic)B4IButtonWrapper* _btncancel_new_address;
@property (nonatomic)B4ILabelWrapper* _lblpostal_enter;
@property (nonatomic)B4ITextFieldWrapper* _txtpostal_enter;
@property (nonatomic)B4IMap* _listaddresscache;
@property (nonatomic)int _choosenaddress4edit;
@property (nonatomic)B4ILabelWrapper* _lbldefault;
@property (nonatomic)B4IList* _listaddressid;
@property (nonatomic)NSString* _choosencity;
@property (nonatomic)B4IPanelWrapper* _pnlmenu;
@property (nonatomic)b4i_mytoastmessageshow* _toast;
@property (nonatomic)B4IPanelWrapper* _pnlloading;
@property (nonatomic)B4ILabelWrapper* _lblpb;
@property (nonatomic)B4IPanelWrapper* _pnlmain;
@property (nonatomic)NSString* _subscribestate;
@property (nonatomic)B4ILabelWrapper* _lblreturn_title;
@property (nonatomic)B4ILabelWrapper* _lblreturn_state;
@property (nonatomic)B4IButtonWrapper* _btnreturn_details;
@property (nonatomic)B4ILabelWrapper* _lblprofile;
@property (nonatomic)B4ILabelWrapper* _lblorders;
@property (nonatomic)B4ILabelWrapper* _lblnewaddress1;
@property (nonatomic)B4ILabelWrapper* _lblnewsletter;
@property (nonatomic)B4ILabelWrapper* _lblreturns;
@property (nonatomic)B4IButtonWrapper* _btnprofile;
@property (nonatomic)B4IButtonWrapper* _btnpasswords;
@property (nonatomic)B4IButtonWrapper* _btnorders;
@property (nonatomic)B4IButtonWrapper* _btnaddress;
@property (nonatomic)B4IButtonWrapper* _btnscribe;
@property (nonatomic)B4IButtonWrapper* _btnreturns;
@property (nonatomic)B4ILabelWrapper* _lblnewaddress;
@property (nonatomic)B4ILabelWrapper* _lblpasswords;
@property (nonatomic)B4ILabelWrapper* _lbladdress1;
@property (nonatomic)B4ILabelWrapper* _lblnewsletteroption;
@property (nonatomic)B4ISwitchWrapper* _rbyes;
@property (nonatomic)B4IButtonWrapper* _btnapply_newsletter;
@property (nonatomic)B4IPanelWrapper* _pnlaction;
@property (nonatomic)B4ILabelWrapper* _lbldefault_address;
@property (nonatomic)B4ILabelWrapper* _lbledit_address;
@property (nonatomic)B4ILabelWrapper* _lbldelete_address;
@property (nonatomic)NSString* _choosenaddressid;
@property (nonatomic)NSString* _choosenaddressvalue;
@property (nonatomic)B4IButtonWrapper* _btnback_menu;
@property (nonatomic)B4ILabelWrapper* _lblback_menu;
@property (nonatomic)B4ILabelWrapper* _lblpassword_title;
@property (nonatomic)B4ITextFieldWrapper* _txtpassword2;
@property (nonatomic)B4ILabelWrapper* _lblpassword2;
@property (nonatomic)B4IPanelWrapper* _pnldetails_return;
@property (nonatomic)B4IScrollView* _sv_return_details;
@property (nonatomic)B4IButtonWrapper* _btncancel_return;
@property (nonatomic)B4IScrollView* _svparent;
@property (nonatomic)B4IScrollView* _svnewsletter;
@property (nonatomic)B4ILabelWrapper* _lblno;
@property (nonatomic)B4ILabelWrapper* _lblyes;
@property (nonatomic)B4IScrollView* _svpassword;
@property (nonatomic)B4IScrollView* _svorders;
@property (nonatomic)B4IScrollView* _svaddress;
@property (nonatomic)B4ILabelWrapper* _lbladdress_1;
@property (nonatomic)B4IPanelWrapper* _pnlaction_address;
@property (nonatomic)B4IScrollView* _svadd_address;
@property (nonatomic)B4ILabelWrapper* _lbldivider;
@property (nonatomic)B4IButtonWrapper* _btnopen;
@property (nonatomic)B4ILabelWrapper* _lbldivider_return;
@property (nonatomic)b4i_main* _main;
@property (nonatomic)b4i_actmenu* _actmenu;
@property (nonatomic)b4i_library* _library;
@property (nonatomic)b4i_actsearch* _actsearch;
@property (nonatomic)b4i_actregister* _actregister;
@property (nonatomic)b4i_actcontact* _actcontact;
@property (nonatomic)b4i_actproduct* _actproduct;
@property (nonatomic)b4i_actpicture* _actpicture;
@property (nonatomic)b4i_actdoorder* _actdoorder;
@property (nonatomic)b4i_actcategory* _actcategory;
@property (nonatomic)b4i_actpayment* _actpayment;
@property (nonatomic)b4i_actpush* _actpush;
@property (nonatomic)b4i_pushnotification* _pushnotification;
@property (nonatomic)b4i_actlogin* _actlogin;
@property (nonatomic)b4i_actbasket* _actbasket;
@property (nonatomic)b4i_actproducts* _actproducts;
@property (nonatomic)b4i_actsms* _actsms;
@property (nonatomic)b4i_actorderdetails* _actorderdetails;
@property (nonatomic)b4i_modshare* _modshare;
@property (nonatomic)b4i_acterrorinternet* _acterrorinternet;
@property (nonatomic)b4i_httputils2service* _httputils2service;
@property (nonatomic)b4i_cachedata* _cachedata;
@property (nonatomic)b4i_dateutils* _dateutils;
@property (nonatomic)b4i_bookmark* _bookmark;
@property (nonatomic)b4i_actabout* _actabout;
@property (nonatomic)b4i_actshow* _actshow;
@property (nonatomic)b4i_actweb* _actweb;
@property (nonatomic)b4i_actsetting* _actsetting;
@property (nonatomic)b4i_actreview* _actreview;
@property (nonatomic)b4i_peroperties* _peroperties;
- (NSString*)  _returndetails_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _returns_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _startactivity;
- (NSString*)  _subsribe_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _tmropenmenu_tick;
- (NSString*)  _tomixcase:(NSString*) _entry;
- (NSString*)  _txtcountry_itemselected:(int) _column :(int) _row;
- (NSString*)  _txtfax_focuschanged:(BOOL) _hasfocus;
- (NSString*)  _txtphone_focuschanged:(BOOL) _hasfocus;
- (NSString*)  _updatedetails_receive:(B4IMap*) _res :(NSString*) _cat;
@end
