#import "iCore.h"
#import "iHttp.h"
#import "iStringUtils.h"
#import "iSQL.h"
#import "iPhone.h"
#import "iJSON.h"
#import "iHUD.h"
#import "iNetwork.h"
#import "iEncryption.h"
#import "iRandomAccessFile.h"
#import "iSideMenu.h"
#import "iReleaseLogger.h"
@class b4i_main;
@class b4i_actmenu;
@class b4i_library;
@class b4i_actsearch;
@class b4i_actregister;
@class b4i_actaccount;
@class b4i_actcontact;
@class b4i_actproduct;
@class b4i_actpicture;
@class b4i_actdoorder;
@class b4i_actcategory;
@class b4i_actpayment;
@class b4i_actpush;
@class b4i_pushnotification;
@class b4i_actlogin;
@class b4i_actbasket;
@class b4i_actproducts;
@class b4i_actsms;
@class b4i_actorderdetails;
@class b4i_modshare;
@class b4i_acterrorinternet;
@class b4i_httputils2service;
@class b4i_cachedata;
@class b4i_dateutils;
@class b4i_bookmark;
@class b4i_actabout;
@class b4i_actshow;
@class b4i_actweb;
@class b4i_actsetting;
@class b4i_actreview;
@class b4i_peroperties;
@class _responseadditem;
@class b4i_imagedownloader;
@class _multipartfiledata;
@class b4i_httpjob;
@class b4i_clspreferencemanager;
@class b4i_slidemenu;
@class b4i_richstring;
@class b4i_html;
@class b4i_mytoastmessageshow;
@class b4i_customlistview;
@class _period;
@class b4i_imagezoom;
@interface b4i_opencart : B4IClass
- (NSString*)  _add2cart:(NSObject*) _module :(NSString*) _event :(NSString*) _sid :(NSString*) _scount :(B4IMap*) _soptions;
- (NSString*)  _addaddress:(NSObject*) _module :(NSString*) _event :(B4IMap*) _sdata :(BOOL) _ispayment;
- (NSString*)  _addaddressuser:(NSObject*) _module :(NSString*) _event :(B4IMap*) _sdata;
- (NSString*)  _addcoupon:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _addreviewproduct:(NSObject*) _module :(NSString*) _event :(NSString*) _sid :(NSString*) _sname :(NSString*) _stext :(NSString*) _srating;
- (NSString*)  _addreward:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _addvoucher:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _checksumlocal:(B4IList*) _data;
- (NSString*)  _checksumonline:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _class_globals;
@property (nonatomic)b4i_httpjob* _hu;
@property (nonatomic)iStringUtils* _su;
@property (nonatomic)NSString* _my_url;
@property (nonatomic)NSString* _api_url;
@property (nonatomic)NSString* _evt;
@property (nonatomic)NSObject* _smodule;
@property (nonatomic)NSString* _currentcategory;
@property (nonatomic)b4i_main* _main;
@property (nonatomic)b4i_actmenu* _actmenu;
@property (nonatomic)b4i_library* _library;
@property (nonatomic)b4i_actsearch* _actsearch;
@property (nonatomic)b4i_actregister* _actregister;
@property (nonatomic)b4i_actaccount* _actaccount;
@property (nonatomic)b4i_actcontact* _actcontact;
@property (nonatomic)b4i_actproduct* _actproduct;
@property (nonatomic)b4i_actpicture* _actpicture;
@property (nonatomic)b4i_actdoorder* _actdoorder;
@property (nonatomic)b4i_actcategory* _actcategory;
@property (nonatomic)b4i_actpayment* _actpayment;
@property (nonatomic)b4i_actpush* _actpush;
@property (nonatomic)b4i_pushnotification* _pushnotification;
@property (nonatomic)b4i_actlogin* _actlogin;
@property (nonatomic)b4i_actbasket* _actbasket;
@property (nonatomic)b4i_actproducts* _actproducts;
@property (nonatomic)b4i_actsms* _actsms;
@property (nonatomic)b4i_actorderdetails* _actorderdetails;
@property (nonatomic)b4i_modshare* _modshare;
@property (nonatomic)b4i_acterrorinternet* _acterrorinternet;
@property (nonatomic)b4i_httputils2service* _httputils2service;
@property (nonatomic)b4i_cachedata* _cachedata;
@property (nonatomic)b4i_dateutils* _dateutils;
@property (nonatomic)b4i_bookmark* _bookmark;
@property (nonatomic)b4i_actabout* _actabout;
@property (nonatomic)b4i_actshow* _actshow;
@property (nonatomic)b4i_actweb* _actweb;
@property (nonatomic)b4i_actsetting* _actsetting;
@property (nonatomic)b4i_actreview* _actreview;
@property (nonatomic)b4i_peroperties* _peroperties;
- (NSString*)  _clearcart:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _clearcartafterpayment:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _contactus:(NSObject*) _module :(NSString*) _event :(NSString*) _semail :(NSString*) _sname :(NSString*) _stext;
- (NSString*)  _customsearchproduct:(NSObject*) _module :(NSString*) _event :(B4IMap*) _sfield :(int) _limit;
- (NSString*)  _deleteaddressuser:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _deleteproductfromcart:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _editaddressuser:(NSObject*) _module :(NSString*) _event :(B4IMap*) _sdata :(NSString*) _sid;
- (NSString*)  _forgotpassword:(NSObject*) _module :(NSString*) _event :(NSString*) _semail;
- (int)  _getcartcount;
- (NSString*)  _getcarts:(NSObject*) _module :(NSString*) _event;
- (B4IMap*)  _getcarttotal:(B4IList*) _data;
- (NSString*)  _getcategory:(NSObject*) _module :(NSString*) _event :(NSString*) _sparentid;
- (NSString*)  _getcategoryproducts:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _getcity:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _getcountry:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getcurrenttoken;
- (NSString*)  _getinformation:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getinformationdetailsid:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _getlanguages:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getmanufactureproduct:(NSString*) _sid :(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getmanufacturers:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getorders:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _getpaymentmethods:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getproductclass:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getreturns:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _getshipmethods:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getslideshow:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getspecialproduct:(NSString*) _category :(BOOL) _paging :(int) _limit :(NSObject*) _module :(NSString*) _event;
- (NSString*)  _getstore:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _gettoken:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _geturl;
- (NSString*)  _initialize:(B4I*) _ba;
- (NSString*)  _jobdone:(b4i_httpjob*) _job;
- (NSString*)  _listaddressuser:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _login:(NSObject*) _module :(NSString*) _event :(NSString*) _semail :(NSString*) _spassword;
- (NSString*)  _loginuser:(NSObject*) _module :(NSString*) _event :(NSString*) _semail :(NSString*) _spassword;
- (NSString*)  _loginusersocial:(NSObject*) _module :(NSString*) _event :(NSString*) _semail :(NSString*) _saccesstoken :(NSString*) _sprovider;
- (NSString*)  _logout:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _paymentorder:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _productdetails:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _register:(NSObject*) _module :(NSString*) _event :(B4IMap*) _data :(BOOL) _isguest;
- (NSString*)  _relatedproduct:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
- (NSString*)  _requestreturn:(NSObject*) _module :(NSString*) _event :(B4IMap*) _sdata;
- (NSString*)  _saveorder:(NSObject*) _module :(NSString*) _event :(BOOL) _isonlysave;
- (NSString*)  _saveordersimple:(NSObject*) _module :(NSString*) _event :(BOOL) _isonlysave;
- (NSString*)  _searchproduct:(NSObject*) _module :(NSString*) _event :(NSString*) _sfield;
- (NSString*)  _searchproduct2:(NSObject*) _module :(NSString*) _event :(NSString*) _sfield;
- (NSString*)  _setdefaultx_oc:(B4IHttpRequest*) _request;
- (NSString*)  _setguestshipmethods:(NSObject*) _module :(NSString*) _event :(B4IMap*) _sdata;
- (NSString*)  _setpaymentmethods:(NSObject*) _module :(NSString*) _event :(NSString*) _sid :(NSString*) _comment;
- (NSString*)  _setshipmethods:(NSObject*) _module :(NSString*) _event :(NSString*) _sid :(NSString*) _comment;
- (NSString*)  _setstoreid:(B4IHttpRequest*) _request;
- (NSString*)  _subscribe:(NSObject*) _module :(NSString*) _event :(BOOL) _subscribes;
- (NSString*)  _updatepassworduser:(NSObject*) _module :(NSString*) _event :(NSString*) _spassword;
- (NSString*)  _updateproductcart:(NSObject*) _module :(NSString*) _event :(NSString*) _sid :(NSString*) _scount;
- (NSString*)  _updateuserdetails:(NSObject*) _module :(NSString*) _event :(B4IMap*) _sdata;
- (NSString*)  _userdetails:(NSObject*) _module :(NSString*) _event;
- (NSString*)  _userorders:(NSObject*) _module :(NSString*) _event :(NSString*) _sid :(BOOL) _isrecorder;
- (NSString*)  _wishlist:(NSObject*) _module :(NSString*) _event :(NSString*) _sid;
@end
