#import "iCore.h"
#import "iHttp.h"
#import "iStringUtils.h"
#import "iSQL.h"
#import "iPhone.h"
#import "iJSON.h"
#import "iHUD.h"
#import "iNetwork.h"
#import "iEncryption.h"
#import "iRandomAccessFile.h"
#import "iSideMenu.h"
#import "iReleaseLogger.h"
@class b4i_main;
@class b4i_actmenu;
@class b4i_actsearch;
@class b4i_actregister;
@class b4i_actaccount;
@class b4i_actcontact;
@class b4i_actproduct;
@class b4i_actpicture;
@class b4i_actdoorder;
@class b4i_actcategory;
@class b4i_actpayment;
@class b4i_actpush;
@class b4i_pushnotification;
@class b4i_actlogin;
@class b4i_actbasket;
@class b4i_actproducts;
@class b4i_actsms;
@class b4i_actorderdetails;
@class b4i_modshare;
@class b4i_acterrorinternet;
@class b4i_httputils2service;
@class b4i_cachedata;
@class b4i_dateutils;
@class b4i_bookmark;
@class b4i_actabout;
@class b4i_actshow;
@class b4i_actweb;
@class b4i_actsetting;
@class b4i_actreview;
@class b4i_peroperties;
@class _responseadditem;
@class b4i_imagedownloader;
@class b4i_opencart;
@class _multipartfiledata;
@class b4i_httpjob;
@class b4i_clspreferencemanager;
@class b4i_slidemenu;
@class b4i_richstring;
@class b4i_html;
@class b4i_mytoastmessageshow;
@class b4i_customlistview;
@class _period;
@class b4i_imagezoom;
@interface b4i_library : B4IStaticModule
- (NSString*)  _add2cart:(NSString*) _sid :(NSString*) _scount :(NSObject*) _smodule;
- (NSString*)  _addhidekeyboardtoview:(NSObject*) _textfield1 :(B4IPanelWrapper*) _container;
- (NSString*)  _addproduct2panel:(B4IScrollView*) _scrollview1 :(int) _left :(B4IArray*) _dimension :(B4IMap*) _temp;
- (NSString*)  _addtabbar:(B4IPage*) _page;
- (NSString*)  _centerview:(B4IViewWrapper*) _v :(B4IViewWrapper*) _parent;
- (NSString*)  _centerview2:(B4IViewWrapper*) _v :(B4IViewWrapper*) _parent;
- (NSString*)  _changefont:(B4IPanelWrapper*) _root;
- (NSString*)  _changenavigationcolor;
- (NSString*)  _converthex2int:(NSString*) _hex;
- (NSString*)  _decrypt:(NSString*) _encrypteddata;
- (NSString*)  _discountprice:(NSString*) _price :(B4ILabelWrapper*) _label1;
- (NSString*)  _discountstylelabel:(NSString*) _price :(NSString*) _finalprice :(B4ILabelWrapper*) _label1;
- (NSString*)  _encrypt:(NSString*) _data :(NSString*) _password;
- (NSString*)  _fullscreenapp:(B4IApplicationWrapper*) _app1;
- (NSString*)  _getbuttonstate:(B4IButtonWrapper*) _button1;
- (NSString*)  _getdate:(NSString*) _date1;
- (float)  _getdevicephysicalsize;
- (NSString*)  _getfilename:(NSString*) _fullpath;
- (B4IFontWrapper*)  _getfont:(int) _fontsize;
- (int)  _getheight;
- (int)  _getlimitloaditem;
- (B4IViewWrapper*)  _getparent:(B4IViewWrapper*) _view1;
- (B4IArray*)  _getparentpaneldimension:(NSString*) _layoutname;
- (NSString*)  _getstringresourse:(NSString*) _key;
- (NSString*)  _getstringresourse2:(NSString*) _key;
- (int)  _getwidth;
- (BOOL)  _internetstate;
- (BOOL)  _isenglish;
- (BOOL)  _isenglish2:(NSString*) _lang;
- (BOOL)  _ispersian;
- (BOOL)  _ispersian2:(NSString*) _lang;
- (NSString*)  _julian2persian:(int) _year :(int) _month :(int) _day :(NSString*) _seprator;
- (NSString*)  _labelspace:(B4IViewWrapper*) _view1 :(float) _space;
- (NSString*)  _loadlanguage:(NSString*) _lang;
- (int)  _loadproduct:(B4IList*) _res :(int) _defaulttop :(B4IScrollView*) _scrollview1;
- (int)  _loadproducthorizontalscroll:(B4IList*) _res :(B4IScrollView*) _scrollview1;
- (NSString*)  _loadtheme;
- (NSString*)  _makedatedialog:(NSString*) _year :(NSString*) _month :(NSString*) _day :(B4IPanelWrapper*) _p1;
- (NSString*)  _paddinglabel:(B4ILabelWrapper*) _lbl :(int) _left :(int) _top :(int) _right :(int) _bottom;
- (B4IArray*)  _parsedate:(NSString*) _date;
- (B4IArray*)  _parsetime:(NSString*) _time;
- (NSString*)  _process_globals;
@property (nonatomic)B4ISettings* _setting;
@property (nonatomic)NSString* _stringresourse;
@property (nonatomic)B4IPage* _refererpage;
@property (nonatomic)iHUD* _hud;
@property (nonatomic)BOOL _paymentsuccess;
@property (nonatomic)B4IApplicationWrapper* _application;
@property (nonatomic)B4INotificationWrapper* _ln;
@property (nonatomic)B4INavigationControllerWrapper* _navcontrol;
@property (nonatomic)B4IPage* _mainpage;
@property (nonatomic)B4IPage* _errornetpage;
@property (nonatomic)B4IPage* _menupage;
@property (nonatomic)B4IPage* _categorypage;
@property (nonatomic)B4IPage* _productpage;
@property (nonatomic)B4IPage* _pagebasket;
@property (nonatomic)B4IPage* _accountpage;
@property (nonatomic)B4IPage* _doorderpage;
@property (nonatomic)B4IMap* _token;
@property (nonatomic)B4IMap* _cartdetails;
@property (nonatomic)NSString* _currlang;
@property (nonatomic)NSString* _currcurrency;
@property (nonatomic)NSString* _storeid;
@property (nonatomic)b4i_clspreferencemanager* _manager;
@property (nonatomic)BOOL _firstrun;
@property (nonatomic)B4IList* _imagesslideshow;
@property (nonatomic)B4IList* _imagesslideshowproduct;
@property (nonatomic)B4IList* _featureproduct;
@property (nonatomic)B4IList* _bestproduct;
@property (nonatomic)B4IList* _newproduct;
@property (nonatomic)B4IList* _listslideshow;
@property (nonatomic)B4IList* _listmanufacturers;
@property (nonatomic)B4IList* _listinformation;
@property (nonatomic)NSString* _wishlist;
@property (nonatomic)int _theme_header;
@property (nonatomic)int _theme_footer;
@property (nonatomic)int _theme_background;
@property (nonatomic)B4IList* _coupons;
@property (nonatomic)B4IMap* _language;
@property (nonatomic)B4IApplicationWrapper* _app;
@property (nonatomic)B4IArray* _tempdimension;
@property (nonatomic)NSString* _productchoosenid;
@property (nonatomic)B4IMap* _logindetails;
@property (nonatomic)B4IPage* _lastpage;
@property (nonatomic)int _positive;
@property (nonatomic)int _negative;
@property (nonatomic)int _cancel;
@property (nonatomic)B4IMap* _guestlogin;
@property (nonatomic)int _choosenaddress;
@property (nonatomic)B4IPanelWrapper* _pitemdefault;
@property (nonatomic)B4IPanelWrapper* _pnlcustomdialog;
@property (nonatomic)NSString* _key_app;
@property (nonatomic)b4i_main* _main;
@property (nonatomic)b4i_actmenu* _actmenu;
@property (nonatomic)b4i_actsearch* _actsearch;
@property (nonatomic)b4i_actregister* _actregister;
@property (nonatomic)b4i_actaccount* _actaccount;
@property (nonatomic)b4i_actcontact* _actcontact;
@property (nonatomic)b4i_actproduct* _actproduct;
@property (nonatomic)b4i_actpicture* _actpicture;
@property (nonatomic)b4i_actdoorder* _actdoorder;
@property (nonatomic)b4i_actcategory* _actcategory;
@property (nonatomic)b4i_actpayment* _actpayment;
@property (nonatomic)b4i_actpush* _actpush;
@property (nonatomic)b4i_pushnotification* _pushnotification;
@property (nonatomic)b4i_actlogin* _actlogin;
@property (nonatomic)b4i_actbasket* _actbasket;
@property (nonatomic)b4i_actproducts* _actproducts;
@property (nonatomic)b4i_actsms* _actsms;
@property (nonatomic)b4i_actorderdetails* _actorderdetails;
@property (nonatomic)b4i_modshare* _modshare;
@property (nonatomic)b4i_acterrorinternet* _acterrorinternet;
@property (nonatomic)b4i_httputils2service* _httputils2service;
@property (nonatomic)b4i_cachedata* _cachedata;
@property (nonatomic)b4i_dateutils* _dateutils;
@property (nonatomic)b4i_bookmark* _bookmark;
@property (nonatomic)b4i_actabout* _actabout;
@property (nonatomic)b4i_actshow* _actshow;
@property (nonatomic)b4i_actweb* _actweb;
@property (nonatomic)b4i_actsetting* _actsetting;
@property (nonatomic)b4i_actreview* _actreview;
@property (nonatomic)b4i_peroperties* _peroperties;
- (NSString*)  _redstring:(NSString*) _str :(B4ILabelWrapper*) _label;
- (NSString*)  _regexreplace:(NSString*) _pattern :(NSString*) _text :(NSString*) _replacement;
- (B4IBitmap*)  _resizebitmap:(B4IBitmap*) _bmp :(float) _scale;
- (NSString*)  _setfont:(B4IViewWrapper*) _views :(NSString*) _fontname :(int) _fontsize;
- (NSString*)  _showcartlabel:(B4ILabelWrapper*) _lbl;
- (NSString*)  _showerrors:(B4IMap*) _rs;
- (NSString*)  _shownotification:(NSString*) _info :(int) _badgenumber;
- (B4IList*)  _string2list:(NSString*) _str;
- (NSString*)  _underline:(NSString*) _str :(B4ILabelWrapper*) _label;
- (NSString*)  _underlinestring:(B4ILabelWrapper*) _label1;
- (BOOL)  _validemail:(NSString*) _emailaddress;
- (BOOL)  _validphonenumber:(NSString*) _id1;
- (BOOL)  _validpostalcode:(NSString*) _code;
@end
@interface _responseadditem:NSObject
@property (nonatomic)BOOL IsInitialized;
@property (nonatomic)B4IViewWrapper* View1;
@property (nonatomic)int Top;
@property (nonatomic)int Left;
-(void)Initialize;
@end
