#import "iCore.h"
#import "iHttp.h"
#import "iStringUtils.h"
#import "iSQL.h"
#import "iPhone.h"
#import "iJSON.h"
#import "iHUD.h"
#import "iNetwork.h"
#import "iEncryption.h"
#import "iRandomAccessFile.h"
#import "iSideMenu.h"
#import "iReleaseLogger.h"
@class b4i_main;
@class b4i_library;
@class b4i_actsearch;
@class b4i_actregister;
@class b4i_actaccount;
@class b4i_actcontact;
@class b4i_actproduct;
@class b4i_actpicture;
@class b4i_actdoorder;
@class b4i_actcategory;
@class b4i_actpayment;
@class b4i_actpush;
@class b4i_pushnotification;
@class b4i_actlogin;
@class b4i_actbasket;
@class b4i_actproducts;
@class b4i_actsms;
@class b4i_actorderdetails;
@class b4i_modshare;
@class b4i_acterrorinternet;
@class b4i_httputils2service;
@class b4i_cachedata;
@class b4i_dateutils;
@class b4i_bookmark;
@class b4i_actabout;
@class b4i_actshow;
@class b4i_actweb;
@class b4i_actsetting;
@class b4i_actreview;
@class b4i_peroperties;
@class _responseadditem;
@class b4i_imagedownloader;
@class b4i_opencart;
@class _multipartfiledata;
@class b4i_httpjob;
@class b4i_clspreferencemanager;
@class b4i_slidemenu;
@class b4i_richstring;
@class b4i_html;
@class b4i_mytoastmessageshow;
@class b4i_customlistview;
@class _period;
@class b4i_imagezoom;
@interface b4i_actmenu : B4IStaticModule
- (NSString*)  _add2cart2_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _addbullet:(int) _size;
- (int)  _addheader:(NSString*) _title :(NSString*) _tag :(int) _top;
- (NSString*)  _addproduct2panel:(B4IScrollView*) _scrollview1 :(int) _left :(B4IArray*) _dimension :(B4IMap*) _temp;
- (NSString*)  _allproduct_receive:(B4IList*) _res :(NSString*) _category;
- (NSString*)  _applysettingchanges;
- (NSString*)  _bestproduct_receive:(B4IList*) _res :(NSString*) _category;
- (NSString*)  _btnadd_2_cart_click;
- (NSString*)  _btnbasket_click;
- (NSString*)  _btncat_click;
- (NSString*)  _btnmenu_click;
- (NSString*)  _btnsearch_click;
- (NSString*)  _carts_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _choosebullet:(int) _i;
- (NSString*)  _featureproduct_receive:(B4IList*) _res :(NSString*) _category;
- (NSString*)  _getcart;
- (NSString*)  _imgads_click;
- (NSString*)  _imgmanufacturers_click;
- (NSString*)  _jobdone:(b4i_httpjob*) _job;
- (NSString*)  _loadmanufacturers:(B4IList*) _res;
- (int)  _loadproducthorizontalscroll:(B4IList*) _res :(B4IScrollView*) _scrollview1;
- (NSString*)  _loadproductsplit:(NSString*) _pa;
- (NSString*)  _loadslideshow:(B4IList*) _res;
- (NSString*)  _logout;
- (NSString*)  _logout_receive:(B4IMap*) _res :(NSString*) _cat;
- (NSString*)  _manufacturers_receive:(B4IMap*) _res1 :(NSString*) _category;
- (NSString*)  _menupage_appear;
- (NSString*)  _menupage_resize:(int) _width :(int) _height;
- (NSString*)  _newproduct_receive:(B4IList*) _res :(NSString*) _category;
- (NSString*)  _pnlover_click;
- (NSString*)  _pnlover_longclick;
- (NSString*)  _pnloverheader_click;
- (NSString*)  _process_globals;
@property (nonatomic)B4ITimer* _timerpush;
@property (nonatomic)B4IScrollView* _slidepanel1;
@property (nonatomic)B4ITimer* _timerslideshow;
@property (nonatomic)BOOL _isoffline;
@property (nonatomic)B4IScrollView* _svhnewproduct;
@property (nonatomic)B4IScrollView* _svhfeatureproduct;
@property (nonatomic)B4IScrollView* _svhbestproduct;
@property (nonatomic)B4IScrollView* _sv1;
@property (nonatomic)B4ILabelWrapper* _lbltitle;
@property (nonatomic)B4IButtonWrapper* _btnbasket;
@property (nonatomic)B4ILabelWrapper* _lblheadername;
@property (nonatomic)B4ILabelWrapper* _lblnext;
@property (nonatomic)b4i_opencart* _featureproduct;
@property (nonatomic)b4i_opencart* _newproduct;
@property (nonatomic)b4i_opencart* _bestproduct;
@property (nonatomic)b4i_opencart* _slideshow;
@property (nonatomic)b4i_opencart* _opmanufacturers;
@property (nonatomic)B4IPanelWrapper* _pnlheader;
@property (nonatomic)int _offsetslideshow;
@property (nonatomic)B4ILabelWrapper* _lblslidetitle;
@property (nonatomic)B4IPanelWrapper* _pnlheadert;
@property (nonatomic)B4IPanelWrapper* _pnlheaderproduct;
@property (nonatomic)B4IPanelWrapper* _pnlloading;
@property (nonatomic)B4ILabelWrapper* _lblpb;
@property (nonatomic)B4IPanelWrapper* _pnlads;
@property (nonatomic)B4IProgressWrapper* _pbslideshow;
@property (nonatomic)B4IPanelWrapper* _pnloverheader;
@property (nonatomic)B4ILabelWrapper* _lblbasket;
@property (nonatomic)B4IPanelWrapper* _pnlcircle;
@property (nonatomic)B4IList* _bullet;
@property (nonatomic)B4IScrollView* _svh;
@property (nonatomic)b4i_mytoastmessageshow* _mytoastmessageshow1;
@property (nonatomic)B4IButtonWrapper* _btnsearch;
@property (nonatomic)B4IButtonWrapper* _btnmenu;
@property (nonatomic)B4IButtonWrapper* _btncat;
@property (nonatomic)int _topsv;
@property (nonatomic)b4i_slidemenu* _sm;
@property (nonatomic)b4i_main* _main;
@property (nonatomic)b4i_library* _library;
@property (nonatomic)b4i_actsearch* _actsearch;
@property (nonatomic)b4i_actregister* _actregister;
@property (nonatomic)b4i_actaccount* _actaccount;
@property (nonatomic)b4i_actcontact* _actcontact;
@property (nonatomic)b4i_actproduct* _actproduct;
@property (nonatomic)b4i_actpicture* _actpicture;
@property (nonatomic)b4i_actdoorder* _actdoorder;
@property (nonatomic)b4i_actcategory* _actcategory;
@property (nonatomic)b4i_actpayment* _actpayment;
@property (nonatomic)b4i_actpush* _actpush;
@property (nonatomic)b4i_pushnotification* _pushnotification;
@property (nonatomic)b4i_actlogin* _actlogin;
@property (nonatomic)b4i_actbasket* _actbasket;
@property (nonatomic)b4i_actproducts* _actproducts;
@property (nonatomic)b4i_actsms* _actsms;
@property (nonatomic)b4i_actorderdetails* _actorderdetails;
@property (nonatomic)b4i_modshare* _modshare;
@property (nonatomic)b4i_acterrorinternet* _acterrorinternet;
@property (nonatomic)b4i_httputils2service* _httputils2service;
@property (nonatomic)b4i_cachedata* _cachedata;
@property (nonatomic)b4i_dateutils* _dateutils;
@property (nonatomic)b4i_bookmark* _bookmark;
@property (nonatomic)b4i_actabout* _actabout;
@property (nonatomic)b4i_actshow* _actshow;
@property (nonatomic)b4i_actweb* _actweb;
@property (nonatomic)b4i_actsetting* _actsetting;
@property (nonatomic)b4i_actreview* _actreview;
@property (nonatomic)b4i_peroperties* _peroperties;
- (NSString*)  _rerunapp;
- (NSString*)  _resumeapp;
- (NSString*)  _showslidecontent:(B4IMap*) _data;
- (NSString*)  _slideshow_receive:(B4IList*) _res :(NSString*) _category;
- (NSString*)  _slideshowsv_scrollchanged:(int) _offsetx :(int) _offsety;
- (NSString*)  _startactivity;
- (NSString*)  _tmrpush_tick;
- (NSString*)  _tmrslideshow_tick;
- (NSString*)  _updateui;
- (NSString*)  _wishlist_receive:(B4IMap*) _res :(NSString*) _cat;
@end
